[project]
name = "meeting-to-jira-ai"
version = "0.1.0"
description = "AI-powered system that converts meeting transcripts into Jira-ready user stories and tickets"
authors = [
    { name = "amitk4413", email = "amitk4413@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10,<3.13"

dependencies = [
    "python-dotenv",
    "langchain",
    "langchain-community",
    "langchain-groq",
    "langchain-huggingface",
    "langchain-chroma",
    "langchain-text-splitters",
    "langchain-core",
    "pypdf",
    "python-docx",
    "sentence-transformers",
    "streamlit",
    "crewai[tools] (>=1.14.7,<2.0.0)",
    "crewai-tools",
    "jira",
    "openai",
    "langchain-openai (>=1.3.2,<2.0.0)",
    "requests (>=2.34.2,<3.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"